### ISSUE TITLE
Curriculum training & on-the-fly data augmentation

### ISSUE THREAD

**Issue by jelmervdl** [jelmervdl/empty-train#22]
[Describe @XapaJIaMnu's idea here]

**Comment by XapaJIaMnu** [comment]
I am thinking of something like
```yml
datasets:
  - data/clean
  - data/medium
  - data/dirty

stages:
  - start
  - mid
  - end

start:
  - clean 0.8
  - medium 0.2
  - dirty 0
  - until clean 2 # Until two epochs of clean

mid:
  - clean 0.6
  - medium 0.3
  - dirty 0.1
  - until medium 1

end:
  - clean 0.4
  - medium 0.3
  - dirty 0.3
  - until dirty inf

augmentation:
 - capitalise 0.1 # Capitalise 1% of the mini-batches


trainer: /path/to/marian/runme.sh
```
We work with batches. For each `batch` we sample (or take consecutively) 100 lines from all of our corpora according to the probability distribution and feed that to the trainer. The trainer will afterwards do its own buffering/batching.

Once a dataset is exhausted, it should be reshuffled before training can resume.
